"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Building2, Check, ChevronDown, Flower2, Hotel, MessageCircle, Sparkles, Store, Trees } from "lucide-react";
import type { BodyBlock } from "@/lib/api";
import { ProjectRequestForm } from "./ProjectRequestForm";

type Project = { title: string; text: string; kind: string; image: string; tag: string };
const DEFAULT_PROJECTS: Project[] = [
  { title: "Beş Yıldızlı Otel Lobileri", text: "Resepsiyon, lobi ve ortak alanlarda ölçülendirilmiş yapay şimşir, orkide ve dikey bahçe uygulamaları.", kind: "Otel", image: "/decor/hotel-decoration.webp", tag: "Otel & Konaklama" },
  { title: "Prestijli Ofis ve Plaza Tasarımları", text: "Marka kimliğinize uygun, bakım gerektirmeyen biyofilik karşılama ve çalışma alanları.", kind: "Ofis", image: "/decor/office-decoration.webp", tag: "Ofis & Plaza" },
  { title: "Kafe ve Restoran Atmosferi", text: "Sosyal medyada paylaşılmak istenen yeşil duvarlar, masa aranjmanları ve imza köşeleri.", kind: "Kafe", image: "/decor/cafe-restaurant-decoration.webp", tag: "Kafe & Restoran" },
  { title: "Düğün ve Organizasyon Konseptleri", text: "Törenden davet masalarına kadar aynı tasarım dilini sürdüren etkileyici, tekrar kullanılabilir çiçek dekorları.", kind: "Düğün", image: "/decor/wedding-decoration.webp", tag: "Düğün & Davet" },
];
const DEFAULT_SERVICES = [
  ["Otel & Lobi", "Karşılama alanları, kolonlar, resepsiyon ve VIP salonları.", "hotel"],
  ["Ofis & Plaza", "Resepsiyon, toplantı odası ve biyofilik çalışma alanları.", "office"],
  ["Kafe & Restoran", "Yeşil duvar, masa üstü ve fotoğraf köşesi uygulamaları.", "cafe"],
  ["Yapay Şimşir", "UV dayanımlı topiary, çit, seperatör ve cephe çözümleri.", "boxwood"],
  ["Düğün & Davet", "Konsept kemer, sahne, masa ve giriş çiçek tasarımları.", "wedding"],
  ["Proje & Uygulama", "Keşif, 3D sunum, üretim, montaj ve yenileme hizmeti.", "project"],
];
const ICONS = { hotel: Hotel, office: Building2, cafe: Store, boxwood: Trees, wedding: Flower2, project: Sparkles } as const;

export function DecorationExperience({ blocks = [] }: { blocks?: BodyBlock[] }) {
  const settings = blocks.find((b) => b.type === "decor-settings");
  const services = blocks.filter((b) => b.type === "decor-service" && b.enabled !== false && b.value !== "false");
  const savedProjects = blocks.filter((b) => b.type === "decor-project" && b.enabled !== false && b.value !== "false");
  const faqs = blocks.filter((b) => b.type === "decor-faq" && b.enabled !== false && b.value !== "false");
  const videos = blocks.filter((b) => b.type === "decor-video" && b.enabled !== false && b.value !== "false");
  const tours = blocks.filter((b) => b.type === "decor-tour" && b.enabled !== false && b.value !== "false");
  const transformations = blocks.filter((b) => b.type === "decor-before-after" && b.enabled !== false && b.value !== "false");
  const projects: Project[] = savedProjects.length ? savedProjects.map((b) => ({ title: String(b.title || "Proje"), text: String(b.text || ""), kind: String(b.kind || "Proje"), image: String(b.note || "/decor/hotel-decoration.webp"), tag: String(b.label || b.kind || "Proje") })) : DEFAULT_PROJECTS;
  const [filter, setFilter] = useState("Tümü");
  const [openFaq, setOpenFaq] = useState(0);
  const [showAfter, setShowAfter] = useState(true);
  const filters = ["Tümü", ...Array.from(new Set(projects.map((p) => p.kind)))];
  const visible = useMemo(() => filter === "Tümü" ? projects : projects.filter((p) => p.kind === filter), [filter, projects]);
  const hero = String(settings?.note || "/decor/artificial-decoration-hero.webp");
  const whatsapp = `https://wa.me/905074413474?text=${encodeURIComponent("Merhaba, yapay çiçek ve mekan dekorasyonu için ücretsiz keşif ve teklif almak istiyorum.")}`;

  return <main className="bg-[#fcfbfd] text-[#160b25]">
    <section className="relative min-h-[720px] overflow-hidden bg-[#0b0315] text-white">
      <img src={hero} alt="Premium yapay çiçek, yapay şimşir ve otel dekorasyonu" className="absolute inset-0 h-full w-full object-cover object-center" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(10,2,23,.96)_0%,rgba(24,8,49,.82)_38%,rgba(37,13,71,.26)_72%,rgba(9,3,18,.15)_100%)]" />
      <div className="relative mx-auto flex min-h-[720px] max-w-[1440px] items-center px-6 py-24 lg:px-14">
        <div className="max-w-[760px]">
          <span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 py-2 text-[11px] font-bold uppercase tracking-[.24em] text-[#ddd6fe]"><Sparkles className="h-4 w-4" />{String(settings?.label || "ÇİÇEKYOLLA YAPAY ÇİÇEK MERKEZİ")}</span>
          <h1 className="mt-8 font-serif text-5xl font-semibold leading-[.98] md:text-7xl lg:text-[86px]">{String(settings?.title || "Mekanınızın İmzası Doğadan İlham Alsın")}</h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/72">{String(settings?.text || "Otel, ofis, kafe, restoran ve organizasyonlar için tasarımdan uygulamaya premium yapay çiçek, şimşir ve yeşil duvar çözümleri.")}</p>
          <div className="mt-9 flex flex-wrap gap-3"><a href="#ucretsiz-kesif" className="inline-flex items-center gap-2 rounded-full bg-white px-7 py-4 font-bold text-[#6D28D9]">Ücretsiz Keşif İste <ArrowRight className="h-4 w-4" /></a><a href="#projeler" className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/5 px-7 py-4 font-bold">Projeleri İncele</a></div>
          <div className="mt-10 grid max-w-2xl grid-cols-2 gap-3 sm:grid-cols-4">{[["500+","Uygulama"],["12+","Kurumsal Proje"],["15–25 Yıl","Ürün Ömrü"],["Türkiye","Geneli Keşif"]].map(([v,l])=><div key={l} className="rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur"><b className="block text-xl">{v}</b><span className="text-xs text-white/55">{l}</span></div>)}</div>
        </div>
      </div>
    </section>

    <section className="px-6 py-24 lg:px-14"><div className="mx-auto max-w-[1370px]"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#8B5CF6]">Mekana Özel Tasarım</p><div className="mt-4 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-3xl font-serif text-4xl font-semibold md:text-6xl">Her mekanın hikayesine özel, kalıcı bir botanik imza.</h2><p className="max-w-md leading-7 text-[#756a82]">Hazır ürün satmıyoruz; ölçüyor, tasarlıyor, üretiyor ve profesyonel ekibimizle uyguluyoruz.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{(services.length ? services.map((b)=>[String(b.title||"Hizmet"),String(b.text||""),String(b.kind||"project")]) : DEFAULT_SERVICES).map(([title,text,kind])=>{const Icon=ICONS[kind as keyof typeof ICONS]||Sparkles;return <article key={title} className="group rounded-[24px] border border-[#eee8f4] bg-white p-7 shadow-[0_14px_50px_rgba(62,33,88,.06)] transition hover:-translate-y-1 hover:border-[#d8c8f2]"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#F3EEFF] text-[#7C3AED]"><Icon className="h-5 w-5" /></div><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-[#776d82]">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#6D28D9]">Detaylı bilgi <ArrowRight className="h-4 w-4" /></span></article>})}</div></div></section>

    <section id="projeler" className="bg-[#120520] px-6 py-24 text-white lg:px-14"><div className="mx-auto max-w-[1370px]"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#c084fc]">Seçili Projeler</p><h2 className="mt-4 max-w-4xl font-serif text-4xl font-semibold md:text-6xl">Görüldüğü anda kaliteyi hissettiren mekanlar.</h2><div className="mt-8 flex flex-wrap gap-2">{filters.map((item)=><button key={item} onClick={()=>setFilter(item)} className={`rounded-full px-5 py-3 text-sm font-bold transition ${filter===item?"bg-white text-[#6D28D9]":"border border-white/15 bg-white/5 text-white/70 hover:bg-white/10"}`}>{item}</button>)}</div><div className="mt-10 grid gap-5 md:grid-cols-2">{visible.map((p)=><article key={p.title} className="group overflow-hidden rounded-[28px] border border-white/10 bg-white/5"><div className="relative aspect-[16/10] overflow-hidden"><img src={p.image} alt={p.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#10031e] via-transparent to-transparent"/><span className="absolute left-5 top-5 rounded-full border border-white/20 bg-black/25 px-4 py-2 text-[10px] font-bold uppercase tracking-[.2em] backdrop-blur">{p.tag}</span></div><div className="p-7"><h3 className="font-serif text-3xl font-semibold">{p.title}</h3><p className="mt-3 leading-7 text-white/60">{p.text}</p></div></article>)}</div></div></section>

    <section className="px-6 py-24 lg:px-14"><div className="mx-auto max-w-[1370px]"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-[#8B5CF6]">Öncesi / Sonrası</p><h2 className="mt-4 font-serif text-4xl font-semibold md:text-6xl">Dönüşümü görün, farkı hissedin.</h2></div><button onClick={()=>setShowAfter(!showAfter)} className="rounded-full border border-[#d9cced] bg-white px-6 py-3 text-sm font-bold text-[#6D28D9]">{showAfter?"Öncesini Gör":"Sonrasını Gör"}</button></div><div className="mt-10 grid gap-5 md:grid-cols-2">{(transformations.length?transformations.map(b=>({title:String(b.title||"Mekan Dönüşümü"),image:String(b.note||"/decor/hotel-decoration.webp")})):projects.slice(0,2)).map((p)=><article key={p.title} className="overflow-hidden rounded-[26px] border border-[#e9e1f1] bg-white shadow-[0_18px_60px_rgba(40,20,64,.08)]"><div className="relative aspect-[16/9] overflow-hidden bg-[#eaf7f2]"><img src={p.image} alt={`${p.title} ${showAfter?"sonrası":"öncesi"}`} className={`h-full w-full object-cover transition duration-700 ${showAfter?"":"scale-105 grayscale opacity-30 blur-[2px]"}`}/><span className="absolute left-5 top-5 rounded-full bg-[#0D9488] px-4 py-2 text-[10px] font-bold text-white">{showAfter?"SONRA":"ÖNCE"}</span></div><div className="p-6"><h3 className="text-xl font-bold">{p.title}</h3><p className="mt-2 text-sm text-[#776d82]">Keşif, konsept, üretim ve profesyonel uygulama.</p></div></article>)}</div></div></section>

    <section className="bg-[#0e172a] px-6 py-24 text-white lg:px-14"><div className="mx-auto max-w-[1370px]"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#2dd4bf]">Video Galerisi</p><h2 className="mt-4 font-serif text-4xl font-semibold md:text-5xl">Projelerimizi izleyin.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{(videos.length?videos:projects.slice(0,3).map((p,i)=>({title:p.title,text:["Kurulum","Drone","Timelapse"][i],note:p.image,label:""}))).map((v,i)=>{const href=String(v.label||"");const Card=<article className="group overflow-hidden rounded-[24px] border border-white/10 bg-white/5"><div className="relative aspect-video overflow-hidden"><img src={String(v.note||projects[i%projects.length].image)} alt={String(v.title||"Proje videosu")} className="h-full w-full object-cover opacity-70 transition group-hover:scale-105 group-hover:opacity-90"/><span className="absolute left-5 top-5 rounded-full bg-black/50 px-3 py-1 text-[10px] font-bold uppercase">{String(v.text||"Proje")}</span><span className="absolute left-1/2 top-1/2 flex h-14 w-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white/40 bg-white/15 text-xl backdrop-blur">▶</span></div><div className="p-5"><b>{String(v.title||"Proje Videosu")}</b><p className="mt-2 text-xs text-white/45">{href?"İzlemek için açın":"Video bağlantısı admin panelinden eklenebilir"}</p></div></article>;return href.startsWith("http")?<a key={String(v.title)+i} href={href} target="_blank" rel="noreferrer">{Card}</a>:<div key={String(v.title)+i}>{Card}</div>})}</div></div></section>

    <section className="bg-[#eefaf8] px-6 py-24 lg:px-14"><div className="mx-auto max-w-[1370px]"><p className="text-center text-xs font-bold uppercase tracking-[.28em] text-[#0D9488]">Sanal Tur</p><h2 className="mt-4 text-center font-serif text-4xl font-semibold md:text-5xl">360° Proje Turları</h2><p className="mx-auto mt-4 max-w-2xl text-center text-[#6f7d7b]">Uygulamalarımızı ziyaret etmeden önce sanal olarak gezinerek inceleyin.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{(tours.length?tours:projects.slice(0,2).map((p)=>({title:p.title,text:"360° tur bağlantısı admin panelinden eklenebilir",note:p.image,label:""}))).map((tour,i)=>{const href=String(tour.label||"");return <article key={String(tour.title)+i} className="overflow-hidden rounded-[26px] bg-white shadow-[0_16px_50px_rgba(16,80,70,.08)]"><div className="relative aspect-[16/8] overflow-hidden bg-[linear-gradient(120deg,#172554,#0f766e)]"><img src={String(tour.note||projects[i%projects.length].image)} alt="" className="h-full w-full object-cover opacity-55"/><div className="absolute inset-0 flex items-center justify-center">{href.startsWith("http")?<a href={href} target="_blank" rel="noreferrer" className="rounded-full bg-[#082f49]/85 px-6 py-3 font-bold text-white">360° Turu Başlat</a>:<span className="rounded-full bg-[#082f49]/85 px-6 py-3 text-sm font-bold text-white/70">360° bağlantısı bekleniyor</span>}</div></div><div className="p-6"><h3 className="text-xl font-bold">{String(tour.title||"Proje Turu")}</h3><p className="mt-2 text-sm text-[#74817f]">{String(tour.text||"")}</p></div></article>})}</div></div></section>

    <section className="px-6 py-24 lg:px-14"><div className="mx-auto grid max-w-[1370px] gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-[#8B5CF6]">Anahtar Teslim Süreç</p><h2 className="mt-4 font-serif text-4xl font-semibold md:text-5xl">Fikirden son dokunuşa tek ekip.</h2><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#6D28D9] px-7 py-4 font-bold text-white"><MessageCircle className="h-4 w-4"/>Projenizi Anlatın</a></div><div className="grid gap-3">{[["01","Ücretsiz Keşif","Mekanı, ışığı, ölçüleri ve marka dilini birlikte analiz ederiz."],["02","Konsept & Teklif","Malzeme, renk, yoğunluk ve uygulama planını şeffaf teklif ile sunarız."],["03","Üretim & Uygulama","Premium ürünleri hazırlar, profesyonel ekiple zamanında uygularız."],["04","Bakım & Yenileme","Mevsimsel yenileme ve periyodik bakım seçenekleriyle görünümü koruruz."]].map(([n,t,d])=><div key={n} className="grid grid-cols-[55px_1fr] gap-4 rounded-[22px] border border-[#eee8f4] bg-white p-6"><span className="font-serif text-3xl text-[#c4b5fd]">{n}</span><div><b className="text-lg">{t}</b><p className="mt-2 leading-7 text-[#776d82]">{d}</p></div></div>)}</div></div></section>

    <section className="bg-[#F3EEFF] px-6 py-24 lg:px-14"><div className="mx-auto max-w-[1100px]"><p className="text-center text-xs font-bold uppercase tracking-[.28em] text-[#8B5CF6]">Merak Edilenler</p><h2 className="mt-4 text-center font-serif text-4xl font-semibold md:text-5xl">Projenize başlamadan önce.</h2><div className="mt-10 space-y-3">{(faqs.length?faqs.map(b=>[String(b.title||""),String(b.text||"")]):[["Yapay çiçekler gerçekçi görünüyor mu?","Mat dokulu, doğal renk geçişli ve premium segment ürünler kullanıyoruz; ürün seçimi numune ve proje sunumuyla onaylanır."],["Keşif ve tasarım süreci nasıl ilerliyor?","Mekan ölçüsü, ışık, kullanım yoğunluğu ve marka dili analiz edilir; ardından konsept, malzeme ve uygulama teklifi hazırlanır."],["Türkiye genelinde uygulama yapıyor musunuz?","Evet. Projenin kapsamına göre Türkiye genelinde keşif, sevkiyat ve profesyonel uygulama planlıyoruz."],["Kurulumdan sonra destek var mı?","Bakım, temizlik, parça yenileme ve dönemsel konsept güncelleme seçenekleri sunuyoruz."]]).map(([q,a],i)=><div key={q} className="overflow-hidden rounded-2xl border border-[#e3d9f5] bg-white"><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} className="flex w-full items-center justify-between p-6 text-left font-bold">{q}<ChevronDown className={`h-5 w-5 text-[#8B5CF6] transition ${openFaq===i?"rotate-180":""}`}/></button>{openFaq===i?<p className="px-6 pb-6 leading-7 text-[#756a82]">{a}</p>:null}</div>)}</div></div></section>

    <section className="px-6 py-20 lg:px-14"><div className="relative mx-auto max-w-[1370px] overflow-hidden rounded-[30px] bg-[linear-gradient(120deg,#16052b,#6D28D9)] p-10 text-white md:p-16"><div className="absolute right-0 top-0 h-72 w-72 rounded-full bg-[#c084fc]/20 blur-3xl"/><div className="relative max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#ddd6fe]">Ücretsiz Proje Görüşmesi</p><h2 className="mt-4 font-serif text-4xl font-semibold md:text-6xl">Mekanınızı sıradanlıktan çıkaralım.</h2><p className="mt-5 text-lg leading-8 text-white/65">Fotoğraflarınızı ve ölçülerinizi paylaşın; tasarım ekibimiz size özel ilk yönlendirmeyi hazırlasın.</p><div className="mt-8 flex flex-wrap gap-3"><a href={whatsapp} target="_blank" rel="noreferrer" className="rounded-full bg-white px-7 py-4 font-bold text-[#6D28D9]">WhatsApp’tan Teklif Al</a><Link href="/kurumsal" className="rounded-full border border-white/25 px-7 py-4 font-bold">Kurumsal Çözümler</Link></div></div></div></section>
    <ProjectRequestForm />
  </main>;
}
