"use client";
import { FormEvent, useState } from "react";
import { Building2, Check, Gift, Send, Sparkles, Users } from "lucide-react";

export type CorporateService={title:string;description:string;badge:string;features:string[];price:string};
export type CorporateField={label:string;type:string;placeholder:string;required:boolean};
const ICONS=[Building2,Sparkles,Gift,Users];

export function CorporateExperience({services,fields}:{services:CorporateService[];fields:CorporateField[]}){
 const [selected,setSelected]=useState(services[0]?.title||"Kurumsal Teklif");
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const lines=[`Hizmet: ${selected}`,...fields.map(f=>`${f.label}: ${String(data.get(f.label)||"")}`)];window.location.href=`mailto:info@cicekyolla.com.tr?subject=${encodeURIComponent(`Kurumsal Teklif — ${selected}`)}&body=${encodeURIComponent(lines.join("\n"))}`;}
 return <>
  <section className="relative overflow-hidden bg-[#0b0319] px-6 py-24 text-white lg:px-14 lg:py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_28%,rgba(168,85,247,.34),transparent_35%),radial-gradient(circle_at_18%_85%,rgba(76,29,149,.32),transparent_40%)]"/><div className="relative mx-auto max-w-[1320px]"><div className="inline-flex rounded-full border border-white/15 bg-white/10 px-5 py-2 text-xs font-bold uppercase tracking-[.22em] text-[#ddd6fe]">Kurumsal Hizmetler</div><h1 className="mt-8 max-w-4xl font-serif text-5xl font-semibold leading-[.98] md:text-7xl lg:text-8xl">İşletmeniz İçin<br/><span className="text-[#c084fc]">Premium Çözümler</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#c4b5d4]">Ofisinizden etkinliklerinize, müşteri hediyelerinden çalışan takdirine kadar size özel kurumsal çiçek hizmetleri.</p><a href="#teklif" className="mt-10 inline-flex rounded-full bg-[#8b5cf6] px-8 py-4 font-bold">Teklif Alın</a></div></section>
  <section className="border-b border-[#ede9fe] bg-white"><div className="mx-auto grid max-w-[1320px] grid-cols-2 lg:grid-cols-4">{[["150+","Kurumsal Müşteri"],["5.000+","Yıllık Sipariş"],["%98","Memnuniyet"],["24/7","Kurumsal Destek"]].map(([v,l])=><div key={l} className="border-r border-[#eeeaf3] px-5 py-10 text-center"><strong className="font-serif text-4xl text-[#160d22]">{v}</strong><span className="mt-2 block text-xs uppercase tracking-[.12em] text-[#9b92a7]">{l}</span></div>)}</div></section>
  <section className="bg-[#fbfafd] px-6 py-20 lg:px-14"><div className="mx-auto max-w-[1320px]"><p className="text-center text-xs font-bold uppercase tracking-[.24em] text-[#8b5cf6]">Hizmetlerimiz</p><h2 className="mt-3 text-center font-serif text-5xl font-semibold">Kurumsal Çözümler</h2><div className="mt-12 grid gap-7 lg:grid-cols-2">{services.map((s,i)=>{const Icon=ICONS[i%ICONS.length];return <article key={s.title} className="rounded-[28px] border border-[#e8e1f0] bg-white p-8 shadow-[0_24px_60px_rgba(45,22,72,.07)]"><div className="flex items-start justify-between"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#f5efff] text-[#8b5cf6]"><Icon className="h-6 w-6"/></span>{s.badge&&<span className="rounded-full bg-[#8b5cf6] px-4 py-1.5 text-xs font-bold text-white">{s.badge}</span>}</div><h3 className="mt-8 font-serif text-3xl font-semibold">{s.title}</h3><p className="mt-4 leading-7 text-[#746b80]">{s.description}</p><ul className="mt-7 space-y-3">{s.features.map(x=><li key={x} className="flex items-center gap-3"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#f5f3ff] text-[#8b5cf6]"><Check className="h-3.5 w-3.5"/></span>{x}</li>)}</ul><div className="mt-8 flex items-center justify-between border-t border-[#eeeaf3] pt-6"><strong className="text-[#8b5cf6]">{s.price}</strong><button onClick={()=>{setSelected(s.title);document.getElementById("teklif")?.scrollIntoView({behavior:"smooth"});}} className="font-bold text-[#8b5cf6]">Teklif Al →</button></div></article>})}</div></div></section>
  <section id="teklif" className="bg-white px-6 py-20 lg:px-14"><div className="mx-auto grid max-w-[1180px] gap-10 rounded-[34px] border border-[#e7def2] bg-[#fcfbfd] p-7 shadow-[0_30px_80px_rgba(45,22,72,.09)] lg:grid-cols-[.8fr_1.2fr] lg:p-12"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#8b5cf6]">Kurumsal İş Birliği</p><h2 className="mt-4 font-serif text-4xl font-semibold">İşletmeniz İçin Teklif Alın</h2><p className="mt-5 leading-7 text-[#746b80]">İhtiyacınızı paylaşın. Form, iletişim adresimiz olan info@cicekyolla.com.tr üzerinden teklif ekibimize ulaşır.</p><div className="mt-8 rounded-2xl bg-[#f3edff] p-5 text-sm"><strong className="block text-[#7c3aed]">Seçilen hizmet</strong><span className="mt-2 block">{selected}</span></div></div><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2">{fields.map(f=><label key={f.label} className={f.type==="textarea"?"sm:col-span-2":""}><span className="mb-2 block text-[11px] font-bold uppercase tracking-[.14em] text-[#746b80]">{f.label}{f.required?" *":""}</span>{f.type==="textarea"?<textarea name={f.label} required={f.required} rows={5} placeholder={f.placeholder} className="w-full rounded-2xl border border-[#e3daf0] bg-white p-4 outline-none focus:border-[#8b5cf6]"/>:<input name={f.label} type={f.type} required={f.required} placeholder={f.placeholder} className="h-14 w-full rounded-2xl border border-[#e3daf0] bg-white px-4 outline-none focus:border-[#8b5cf6]"/>}</label>)}<button className="flex h-14 items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-[#7c3aed] to-[#a855f7] font-bold text-white sm:col-span-2"><Send className="h-4 w-4"/>Teklif Talebini Gönder</button></form></div></section>
 </>;
}
